[package]
name = "icons"
version = "0.1.0"
authors = ["ALeX Kazik <alex@kazik.de>"]
edition = "2021"
license = "MIT"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
yew-bootstrap = { path = "../../packages/yew-bootstrap" }

[[bin]]
name = "copy-bootstrap-icons"
