[package]
name = "icons"
version = "0.3.0"
authors = ["ALeX Kazik <alex@kazik.de>"]
edition = "2021"
license = "MIT"

[dependencies]
yew = { version = "0.22", features = ["csr"] }
yew-bootstrap = { path = "../../packages/yew-bootstrap" }

[[bin]]
name = "include-bootstrap-icons"
