[package]
name = "searchable_select"
version = "0.0.1"
authors = ["CÃ©dric Airaud <cairaud@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
yew = { version = "0.22", features = ["csr"] }
yew-bootstrap = { path = "../../packages/yew-bootstrap", features=["searchable_select"] }
