[package]
name = "cards"
version = "0.2.1"
authors = ["CÃ©dric Airaud <cairaud@gmail.com>", "CraftSpider <runetynan@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
yew = { version = "0.22", features = ["csr"] }
yew-bootstrap = { path = "../../packages/yew-bootstrap" }
